function finalU2(){
localStorage.setItem(localStorage.getItem("char:")+']'+':'+'UF~_ATK:',parseInt(localStorage.getItem(localStorage.getItem("char:")+']'+':'+'MOD_racial_1~_ATK:')) + parseInt(localStorage.getItem(localStorage.getItem("char:")+']'+':'+'MOD_racial_2~_ATK:')) + parseInt(localStorage.getItem(localStorage.getItem("char:")+']'+':'+'MOD_levelU~_ATK:')) + parseInt(localStorage.getItem(localStorage.getItem("char:")+']'+':'+'MOD_racial_3~_ATK:')) + parseInt(localStorage.getItem(localStorage.getItem("char:")+']'+':'+'MOD_racial_4~_ATK:')) + parseInt(localStorage.getItem(localStorage.getItem("char:")+']'+':'+'MOD_levelU2~_ATK:')));

localStorage.setItem(localStorage.getItem("char:")+']'+':'+'UF~_DEF:',parseInt(localStorage.getItem(localStorage.getItem("char:")+']'+':'+'MOD_racial_1~_DEF:')) + parseInt(localStorage.getItem(localStorage.getItem("char:")+']'+':'+'MOD_racial_2~_DEF:')) + parseInt(localStorage.getItem(localStorage.getItem("char:")+']'+':'+'MOD_levelU~_DEF:')) + parseInt(localStorage.getItem(localStorage.getItem("char:")+']'+':'+'MOD_racial_3~_DEF:')) +	parseInt(localStorage.getItem(localStorage.getItem("char:")+']'+':'+'MOD_racial_4~_DEF:')) + parseInt(localStorage.getItem(localStorage.getItem("char:")+']'+':'+'MOD_levelU2~_DEF:')));

localStorage.setItem(localStorage.getItem("char:")+']'+':'+'UF~_PW:', parseInt(localStorage.getItem(localStorage.getItem("char:")+']'+':'+'MOD_racial_1~_ATK:')) + parseInt(localStorage.getItem(localStorage.getItem("char:")+']'+':'+'MOD_racial_2~_ATK:')) + parseInt(localStorage.getItem(localStorage.getItem("char:")+']'+':'+'MOD_levelU~_ATK:')) + parseInt(localStorage.getItem(localStorage.getItem("char:")+']'+':'+'MOD_racial_3~_ATK:')) + parseInt(localStorage.getItem(localStorage.getItem("char:")+']'+':'+'MOD_racial_4~_ATK:')) + parseInt(localStorage.getItem(localStorage.getItem("char:")+']'+':'+'MOD_levelU2~_ATK:')) + parseInt(localStorage.getItem(localStorage.getItem("char:")+']'+':'+'MOD_racial_1~_DEF:')) + parseInt(localStorage.getItem(localStorage.getItem("char:")+']'+':'+'MOD_racial_2~_DEF:')) + parseInt(localStorage.getItem(localStorage.getItem("char:")+']'+':'+'MOD_levelU~_DEF:')) + parseInt(localStorage.getItem(localStorage.getItem("char:")+']'+':'+'MOD_racial_3~_DEF:')) + parseInt(localStorage.getItem(localStorage.getItem("char:")+']'+':'+'MOD_racial_4~_DEF:')) + parseInt(localStorage.getItem(localStorage.getItem("char:")+']'+':'+'MOD_levelU2~_DEF:')) + parseInt(localStorage.getItem(localStorage.getItem("char:")+']'+':'+'MOD_racial_1~_PW:')) + parseInt(localStorage.getItem(localStorage.getItem("char:")+']'+':'+'MOD_racial_2~_PW:')) + parseInt(localStorage.getItem(localStorage.getItem("char:")+']'+':'+'MOD_levelU~_PW:')) + parseInt(localStorage.getItem(localStorage.getItem("char:")+']'+':'+'MOD_racial_3~_PW:')) + parseInt(localStorage.getItem(localStorage.getItem("char:")+']'+':'+'MOD_racial_4~_PW:')) + parseInt(localStorage.getItem(localStorage.getItem("char:")+']'+':'+'MOD_levelU2~_PW:')));

localStorage.setItem(localStorage.getItem("char:")+']'+':'+'UF~_HP:', parseInt(localStorage.getItem(localStorage.getItem("char:")+']'+':'+'MOD_racial_1~_HP:')) + parseInt(localStorage.getItem(localStorage.getItem("char:")+']'+':'+'MOD_racial_2~_HP:')) + parseInt(localStorage.getItem(localStorage.getItem("char:")+']'+':'+'MOD_levelU~_HP:')) + parseInt(localStorage.getItem(localStorage.getItem("char:")+']'+':'+'MOD_racial_3~_HP:')) + parseInt(localStorage.getItem(localStorage.getItem("char:")+']'+':'+'MOD_racial_4~_HP:')) + parseInt(localStorage.getItem(localStorage.getItem("char:")+']'+':'+'MOD_levelU2~_HP:')));

localStorage.setItem(localStorage.getItem("char:")+']'+':'+'UF~_MP:', parseInt(localStorage.getItem(localStorage.getItem("char:")+']'+':'+'MOD_racial_1~_MP:')) + parseInt(localStorage.getItem(localStorage.getItem("char:")+']'+':'+'MOD_racial_2~_MP:')) + parseInt(localStorage.getItem(localStorage.getItem("char:")+']'+':'+'MOD_levelU~_MP:')) +parseInt(localStorage.getItem(localStorage.getItem("char:")+']'+':'+'MOD_racial_3~_MP:')) + parseInt(localStorage.getItem(localStorage.getItem("char:")+']'+':'+'MOD_racial_4~_MP:')) + parseInt(localStorage.getItem(localStorage.getItem("char:")+']'+':'+'MOD_levelU2~_MP:')));
}

